// This is an autogenerated file from Firebase Studio.

'use server';

/**
 * @fileOverview Generates a tailored response to a user's free-form inquiry.
 *
 * - generateInquiryResponse - A function that generates a tailored response to a user's free-form inquiry.
 * - GenerateInquiryResponseInput - The input type for the generateInquiryResponse function.
 * - GenerateInquiryResponseOutput - The return type for the generateInquiryResponse function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const GenerateInquiryResponseInputSchema = z.object({
  inquiry: z.string().describe('The user inquiry.'),
});
export type GenerateInquiryResponseInput = z.infer<typeof GenerateInquiryResponseInputSchema>;

const GenerateInquiryResponseOutputSchema = z.object({
  response: z.string().describe('A tailored response to the user inquiry.'),
});
export type GenerateInquiryResponseOutput = z.infer<typeof GenerateInquiryResponseOutputSchema>;

export async function generateInquiryResponse(input: GenerateInquiryResponseInput): Promise<GenerateInquiryResponseOutput> {
  return generateInquiryResponseFlow(input);
}

const prompt = ai.definePrompt({
  name: 'generateInquiryResponsePrompt',
  input: {schema: GenerateInquiryResponseInputSchema},
  output: {schema: GenerateInquiryResponseOutputSchema},
  prompt: `You are a helpful assistant that provides tailored responses to user inquiries. Please analyze the inquiry and provide a concise and informative response.

Inquiry: {{{inquiry}}}`,
});

const generateInquiryResponseFlow = ai.defineFlow(
  {
    name: 'generateInquiryResponseFlow',
    inputSchema: GenerateInquiryResponseInputSchema,
    outputSchema: GenerateInquiryResponseOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
