
export const marketerTasksData = [
  {
    id: 'TSK-001',
    title: 'Draft Q3 Blog Content Calendar',
    description: 'Plan blog topics for the third quarter, focusing on SEO keywords related to our new product launch. Align topics with the overall content strategy.',
    status: 'In Progress',
    priority: 'High',
    due_date: '2024-08-25',
    assigned_to: 'Alex Ray',
    tags: ['Content', 'SEO'],
    created_at: '2024-07-31',
  },
  {
    id: 'TSK-002',
    title: 'Launch Google Ads Campaign for "Innovate Inc."',
    description: 'Set up and launch a new Google Ads campaign targeting enterprise clients for the "Innovate Inc." project. Monitor initial performance.',
    status: 'Not Started',
    priority: 'Urgent',
    due_date: '2024-08-18',
    assigned_to: 'Dana Scully',
    tags: ['Ads', 'PPC'],
    created_at: '2024-08-04',
  },
  {
    id: 'TSK-003',
    title: 'Design Email Newsletter Template',
    description: 'Create a new, reusable email newsletter template in Mailchimp. The design should be modern, mobile-friendly, and align with our brand refresh.',
    status: 'Completed',
    priority: 'Medium',
    due_date: '2024-07-26',
    assigned_to: 'Alex Ray',
    tags: ['Email', 'Design'],
    created_at: '2024-07-16',
  },
  {
    id: 'TSK-004',
    title: 'Analyze July Social Media Performance',
    description: 'Compile and analyze performance metrics for all social media channels for the month of July. Prepare a summary report with key insights and recommendations.',
    status: 'In Progress',
    priority: 'Medium',
    due_date: '2024-08-22',
    assigned_to: 'Fox Mulder',
    tags: ['Social Media', 'Analytics'],
    created_at: '2024-08-03',
  },
  {
    id: 'TSK-005',
    title: 'Update SEO Meta Descriptions for Service Pages',
    description: 'Review and rewrite meta titles and descriptions for all main service pages to improve click-through rates from SERPs.',
    status: 'Not Started',
    priority: 'High',
    due_date: '2024-08-29',
    assigned_to: 'Dana Scully',
    tags: ['SEO'],
    created_at: '2024-08-02',
  },
  {
    id: 'TSK-006',
    title: 'Schedule August Social Media Posts',
    description: 'Schedule all approved social media content for August across LinkedIn, Twitter, and Instagram using Buffer.',
    status: 'Completed',
    priority: 'Medium',
    due_date: '2024-08-03',
    assigned_to: 'Fox Mulder',
    tags: ['Social Media'],
    created_at: '2024-07-28',
  },
  {
    id: 'TSK-007',
    title: 'A/B Test "Get a Quote" CTA Button',
    description: 'Set up an A/B test on the homepage to compare the performance of two different colors for the "Get a Quote" CTA button.',
    status: 'On Hold',
    priority: 'Low',
    due_date: '2024-09-14',
    assigned_to: 'Alex Ray',
    tags: ['CRO', 'Analytics'],
    created_at: '2024-07-21',
  },
  {
    id: 'TSK-008',
    title: 'Write Case Study for "Quantum Solutions" Project',
    description: 'Interview the project lead and write a detailed case study on the successful "Quantum Solutions" e-commerce backend refactor. Highlight key results and ROI.',
    status: 'In Progress',
    priority: 'High',
    due_date: '2024-09-04',
    assigned_to: 'Alex Ray',
    tags: ['Content', 'Case Study'],
    created_at: '2024-08-01',
  },
  {
    id: 'TSK-009',
    title: 'Create Q3 Email Welcome Automation Series',
    description: 'Develop a 3-part email automation series for new subscribers to nurture leads and introduce them to our core services.',
    status: 'Not Started',
    priority: 'Medium',
    due_date: '2024-09-09',
    assigned_to: 'Dana Scully',
    tags: ['Email', 'Automation'],
    created_at: '2024-08-04',
  },
  {
    id: 'TSK-010',
    title: 'Research Competitor Backlink Strategies',
    description: 'Use Ahrefs or SEMrush to analyze the backlink profiles of our top 3 competitors. Identify new link-building opportunities.',
    status: 'Not Started',
    priority: 'Low',
    due_date: '2024-09-29',
    assigned_to: 'Fox Mulder',
    tags: ['SEO', 'Research'],
    created_at: '2024-08-04',
  },
];
