
export const availableNetworkProjectsData = [
  {
    id: 'net_proj_001',
    name: 'Cloud Infrastructure Migration to AWS',
    client: 'Innovate Inc.',
    postedBy: 'Alex Ray',
    description: 'Migrate existing on-premise server infrastructure to a scalable AWS environment. Responsibilities include setting up VPCs, EC2 instances, RDS for database, and configuring security groups and IAM roles.',
    deadline: '2 Months',
    budget: '₹1,440,000',
    techStack: ['AWS', 'Terraform', 'VPC', 'Linux', 'Security'],
    status: 'Live',
  },
  {
    id: 'net_proj_002',
    name: 'Corporate Network Security Audit',
    client: 'Quantum Solutions',
    postedBy: 'Alex Ray',
    description: 'Perform a comprehensive security audit of the corporate network across two office locations. Identify vulnerabilities, review firewall configurations, analyze traffic patterns, and provide a detailed report with actionable recommendations.',
    deadline: '3 Weeks',
    budget: '₹640,000',
    techStack: ['Network Security', 'Firewalls', 'Wireshark', 'Penetration Testing'],
    status: 'Live',
  },
  {
    id: 'net_proj_003',
    name: '24/7 Monitoring System Implementation',
    client: 'Starlight Co.',
    postedBy: 'Alex Ray',
    description: 'Implement a robust, 24/7 proactive monitoring and alerting system for a suite of public-facing web applications. The solution should use Prometheus and Grafana for metrics and dashboards, with PagerDuty for incident alerts.',
    deadline: '1 Month',
    budget: '₹800,000',
    techStack: ['Prometheus', 'Grafana', 'Alertmanager', 'PagerDuty', 'Docker'],
    status: 'Live',
  },
  {
    id: 'net_proj_004',
    name: 'On-Call Support Retainer',
    client: 'Future Forward',
    postedBy: 'Alex Ray',
    description: 'Provide on-call support and incident response for a critical AI processing platform. This is a 6-month retainer contract requiring availability for critical incidents outside of standard business hours. SLAs for response time are strict.',
    deadline: '6 Month Contract',
    budget: '₹400,000 / month',
    techStack: ['Incident Response', 'SLA Management', 'Kubernetes', 'GCP'],
    status: 'Live',
  },
];
